-- CREATE TABLE items (
--     id int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
-- 	item_code varchar(10) NOT NULL,
--     description varchar(100) NOT NULL,
--     quantity int NOT NULL,
--     order_id int NOT NULL
-- );


-- CREATE TABLE orders (
--     id int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
--     customer_name varchar(100) NOT NULL,
--     ordered_at varchar(100) NOT NULL
-- );
